// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Payment struct {
	TicketID         int64     `json:"ticket_id"`
	Amount           int32     `json:"amount"`
	CreditCardNumber int32     `json:"credit_card_number"`
	CreatedAt        time.Time `json:"created_at"`
}

type Ticket struct {
	TicketID    int64     `json:"ticket_id"`
	Route       string    `json:"route"`
	TrainNumber int64     `json:"train_number"`
	CoachNumber int32     `json:"coach_number"`
	SeatNumber  int32     `json:"seat_number"`
	BookingDate time.Time `json:"booking_date"`
	TripDate    time.Time `json:"trip_date"`
	Fare        int32     `json:"fare"`
	Email       string    `json:"email"`
}

type Timetable struct {
	Route     string    `json:"route"`
	Arrival   time.Time `json:"arrival"`
	Departure time.Time `json:"departure"`
	Distance  int32     `json:"distance"`
	Price     int32     `json:"price"`
}

type Train struct {
	TrainNumber    int64  `json:"train_number"`
	Type           string `json:"type"`
	Class          string `json:"class"`
	MaxPassengerNo int32  `json:"max_passenger_no"`
	MaxSpeed       int32  `json:"max_speed"`
	Route          string `json:"route"`
}

type User struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
