// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	Createpayment(ctx context.Context, arg CreatepaymentParams) (Payment, error)
	Createticket(ctx context.Context, arg CreateticketParams) (Ticket, error)
	Createtimetable(ctx context.Context, arg CreatetimetableParams) (Timetable, error)
	Createtrain(ctx context.Context, arg CreatetrainParams) (Train, error)
	Createuser(ctx context.Context, arg CreateuserParams) (User, error)
	Deleteticket(ctx context.Context, ticketID int64) error
	Deletetimetable(ctx context.Context, route string) error
	Deletetrain(ctx context.Context, trainNumber int64) error
	Deleteuser(ctx context.Context, email string) error
	Getpayment(ctx context.Context, ticketID int64) (Payment, error)
	Getticket(ctx context.Context, ticketID int64) (Ticket, error)
	Gettimetable(ctx context.Context, route string) (Timetable, error)
	Gettrain(ctx context.Context, trainNumber int64) (Train, error)
	Getuser(ctx context.Context, email string) (User, error)
	Listpayments(ctx context.Context, limit int32) ([]Payment, error)
	Listtickets(ctx context.Context, limit int32) ([]Ticket, error)
	Listtimetables(ctx context.Context, limit int32) ([]Timetable, error)
	Listtrains(ctx context.Context, limit int32) ([]Train, error)
	Listtrainsbyroutes(ctx context.Context, arg ListtrainsbyroutesParams) ([]Train, error)
	Listusers(ctx context.Context, limit int32) ([]User, error)
}

var _ Querier = (*Queries)(nil)
