// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: users.sql

package db

import (
	"context"
)

const createuser = `-- name: Createuser :one
INSERT INTO users(
    email, 
    password
) VALUES (
    $1, $2
) RETURNING email, password
`

type CreateuserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) Createuser(ctx context.Context, arg CreateuserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createuser, arg.Email, arg.Password)
	var i User
	err := row.Scan(&i.Email, &i.Password)
	return i, err
}

const deleteuser = `-- name: Deleteuser :exec
DELETE FROM users
WHERE email = $1
`

func (q *Queries) Deleteuser(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteuser, email)
	return err
}

const getuser = `-- name: Getuser :one
SELECT email, password FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) Getuser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getuser, email)
	var i User
	err := row.Scan(&i.Email, &i.Password)
	return i, err
}

const listusers = `-- name: Listusers :many
SELECT email, password FROM users
ORDER BY email
LIMIT $1
`

func (q *Queries) Listusers(ctx context.Context, limit int32) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listusers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.Email, &i.Password); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
